# GitHub Pages Theme Configuration
theme: jekyll-theme-cayman
title: KineticLake
description: "Cyber-Physical DataOps Platform for Robotic Sensor Fusion & GPS-Denied Localization"
readme_index:
  with_frontmatter: true
